docs: added to the Configuration.md about several auth
artipie/artipie pull request #1014
Opened 2022-02-17 07:55 UTC by dgarus

Closes #999 

- added description of the `env` credentials type
- added description of the `github` credentials type
- added  description of alternative authentication

2022-02-17 07:56 UTC, dgarus commented
@g4s8 
Could you please have a look?

2022-02-17 08:16 UTC, dgarus commented
@g4s8
Could you please have a look?

2022-02-17 14:57 UTC, olenagerasimova requested changes
@dgarus thanks, several language-related comments

2022-02-17 14:57 UTC, olenagerasimova commented on .wiki/Configuration.md
> +process until success with one of them.
"until success with one of them" -> "until one of them is successful"

2022-02-17 16:33 UTC, dgarus commented
@olenagerasimova 
Thank you for the review!
I fixed your comments.

2022-02-18 06:16 UTC, olenagerasimova approved these changes
@dgarus thanks
@g4s8 take a look/merge

2022-02-18 08:58 UTC, merged