feat: add docker-compose.yaml and correct README.md
artipie/artipie pull request #1030
Opened 2022-06-15 13:28 UTC by olenagerasimova

Closes #1028 
Added docker-compose script to run both Artipie and Artipie front, corrected readme. 

Note, that I'm not a devops and have no idea about best practicies for such type of configurations.

2022-06-16 07:57 UTC, dgarus requested changes
@olenagerasimova, pay attention to my comment, please.

2022-06-16 07:57 UTC, dgarus commented on README.md
>  # Quickstart
Currently, we cannot host the data in Google Cloud and HuaweiCloud OBS...

2022-06-16 08:16 UTC, dgarus submitted a review, later dismissed
Thanks!
LGTM

2022-06-16 08:21 UTC, olenagerasimova commented
@dgarus thanks, I've corrected part about storages. Have you tried to run docker-compose? Steps to check everything is working can be the following:
- run docker-compose
- go to dashboard: 
    * login with test user `artipie/artipie`
    * create new binary repository
- put some file into created repository (use `curl PUT` or smth similar)
- get the file from repository (use `curl GET` or smth similar)

2022-06-17 12:10 UTC, olenagerasimova commented
@dgarus I've corrected docker-compose script, storages configuration and readme. 
As for [named volumes](https://docs.docker.com/storage/volumes/#start-a-service-with-volumes) 

> When you start a service and define a volume, each service container uses its own local volume. None of the containers can share this data if you use the local volume driver

Volumes also has some volumes drivers, but most of them are for AWS or Azure or some other cloud storage support, not for simple data sharing. 

That's why I simply added two volumes with some (linux consistent) local directory.

2022-06-17 12:20 UTC, merged