fix: repository port usage
artipie/artipie pull request #1042
Opened 2022-07-14 13:31 UTC by olenagerasimova

Part of #1041 

Fixed cases with repository port:

1) path trimming is necessary when repo port is set (for now, I've only fixed it for files repository and added corresponding tests)
2) repository with port should not be accessible by default port

2022-07-15 10:38 UTC, dgarus requested changes

2022-07-15 10:38 UTC, dgarus commented on src/main/java/com/artipie/SliceFromConfig.java
> +                slice = new TrimPathSlice(
We should use the same approach for all slices.

2022-07-15 10:38 UTC, dgarus commented on src/main/java/com/artipie/http/ArtipieRepositories.java
> +                Slice res = new SliceSimple(new RsRepoNotFound(name));
Think it'll be better to use `else` brunch to create `SliceSimple`.

2022-07-18 07:09 UTC, olenagerasimova commented
@dgarus all fixed and todos added. Please, take a look

2022-07-18 07:55 UTC, dgarus approved these changes
@olenagerasimova thanks!

2022-07-18 07:55 UTC, merged