doc: how to start artipie with maven-proxy repository
artipie/artipie pull request #1061
Opened 2022-07-21 11:49 UTC by dgarus

Closes: #1059 

- written section `how to start artipie with maven-proxy repository`
- fixed maven-proxy example files

2022-07-21 14:03 UTC, olenagerasimova requested changes
@dgarus thanks, please, check my comments

2022-07-21 14:14 UTC, Swizbiz requested changes
please check my comments

2022-07-21 14:33 UTC, dgarus commented on .wiki/Home.md
> +then Artipie service find it while startup and create repository with name `my-maven`.
may be add `will`?

2022-07-22 10:34 UTC, Swizbiz approved these changes
thanks!

2022-07-22 11:05 UTC, merged