doc: added credentials description
artipie/artipie pull request #1066
Opened 2022-07-22 12:11 UTC by olenagerasimova

Part of #1031 
Added detailed description for credentials.

2022-07-25 12:23 UTC, dgarus requested changes
@olenagerasimova thanks!
There is a small comment.

2022-07-25 12:23 UTC, dgarus commented on .wiki/Configuration-Credentials.md
> +If the `type` is set to `github`, GitHub username with `github.com/` prefix and [personal access
It would be clearer to give additionally an example:
```
github.com/{username}
```

2022-07-26 09:28 UTC, olenagerasimova commented
@dgarus thanks, added

2022-07-26 09:32 UTC, dgarus approved these changes
@olenagerasimova thanks!

2022-07-26 09:48 UTC, merged