doc: verification tests
artipie/artipie pull request #1133
Opened 2022-09-12 12:30 UTC by dgarus

part of [445] (https://github.com/artipie/asto/issues/445)

Added a verification tests description to the storage section.

2022-09-12 14:43 UTC, olenagerasimova requested changes
@dgarus thanks, check my comments please

2022-09-12 14:43 UTC, olenagerasimova commented on .wiki/Configuration-Storage.md
> +The `asto-core` module contains verification tests that designed to confirm correctness of a storage implementation.
that -> which are

2022-09-12 14:43 UTC, olenagerasimova commented on .wiki/Configuration-Storage.md
> +A storage verification test class have to extend the `StorageWhiteboxVerification` and provide the `newStorage` method,
have -> has
provide -> implement

2022-09-12 14:43 UTC, olenagerasimova commented on .wiki/Configuration-Storage.md
> +> Note: To avoid affect one test to another, test environment should be returned to initial state before each test.
affect one test to another -> possible mutual affects between tests methods

2022-09-12 14:43 UTC, olenagerasimova commented on .wiki/Configuration-Storage.md
> +> in that case you should override `newBaseForSubStorage` or(and)
"in that case" is not needed here

2022-09-13 06:25 UTC, dgarus commented
@olenagerasimova thanks for the reviw!
I fixed comments. Also, I removed `Rultor.com` label from readme file.

2022-09-13 06:39 UTC, olenagerasimova approved these changes
@dgarus thanks

2022-09-13 06:47 UTC, merged