wiki: describe Artipie's JFR events
artipie/artipie pull request #1221
Opened 2022-12-19 13:48 UTC by dgarus

closes #1203 

- added Artipie's JFR events section

2022-12-19 14:47 UTC, olenagerasimova requested changes
@dgarus thanks, just some cosmetic suggestions

2022-12-19 14:47 UTC, olenagerasimova commented on .wiki/jfr-events.md
> +Artipie generate the following events:
generate -> generateS

2022-12-19 16:02 UTC, dgarus commented
@olenagerasimova thanks! Fixed.

2022-12-20 08:30 UTC, olenagerasimova approved these changes
@dgarus thanks

2022-12-20 08:31 UTC, merged