Keycloak authentication
artipie/artipie pull request #1236
Opened 2023-01-26 08:47 UTC by andpopov

Part of: #24

2023-01-26 08:48 UTC, andpopov commented
@olenagerasimova @dgarus please review

2023-01-26 13:19 UTC, olenagerasimova requested changes
@andpopov thanks, just minor comments and please, pay attention to the CI, it's failing now

2023-01-26 13:19 UTC, olenagerasimova commented on src/main/java/com/artipie/auth/AuthFromKeycloak.java
> +    @SuppressWarnings("PMD.OnlyOneReturn")
this suppression is not required, method has only one return....

2023-01-26 13:19 UTC, olenagerasimova commented on src/test/java/com/artipie/auth/AuthFromKeycloakTest.java
> +public class AuthFromKeycloakTest {
Disable this test on windows, github win actions does not have docker

2023-01-27 07:05 UTC, olenagerasimova submitted a review, later dismissed

2023-01-27 09:08 UTC, dgarus requested changes
Thanks.
There are minor comments, please have a look.

2023-01-27 09:08 UTC, dgarus commented on src/main/java/com/artipie/auth/AuthFromKeycloak.java
> +            return Optional.of(new User(username, roles.stream().toList()));
`new User(username, roles.stream().toList())` can be replaced by `new User(username, roles)`

2023-01-27 10:49 UTC, dgarus approved these changes
lgtm

2023-01-27 11:07 UTC, olenagerasimova approved these changes

2023-01-27 11:09 UTC, dgarus approved these changes

2023-01-27 11:21 UTC, merged