feat: cache authenticated users
artipie/artipie pull request #1243
Opened 2023-02-13 09:31 UTC by olenagerasimova

part of #1237

2023-02-13 11:54 UTC, dgarus requested changes
Thanks!
Please look at my comment.

2023-02-13 11:54 UTC, dgarus commented on src/main/java/com/artipie/settings/cache/CachedUsers.java
> +            () -> this.users.get(key, () -> this.origin.user(username, password))
`byte[]` as a key is a bad solution
```
@Test
void aaa(){
    byte[] a = "aaa".getBytes();
    byte[] b = "aaa".getBytes();

    System.out.println(a.equals(b));
    System.out.println(a.hashCode());
    System.out.println(b.hashCode());
}
```
Output:
false
1238959340
76432244

2023-02-13 15:16 UTC, olenagerasimova commented
@dgarus my bad, used hex string and added test.

2023-02-14 08:09 UTC, dgarus approved these changes
lgtm

2023-02-14 08:23 UTC, olenagerasimova commented
@Swizbiz will you check it or I can merge?

2023-02-16 12:50 UTC, Swizbiz approved these changes
@olenagerasimova thank you. 
Look good to me.

2023-02-16 12:56 UTC, merged