Artipie Dockerfile includes support of all Artipie storage types.
artipie/artipie pull request #1250
Opened 2023-03-01 12:03 UTC by andpopov

Closes #1244

2023-03-01 12:47 UTC, ChGen commented
Maybe we should implement it as maven build profile as a next step, to have cleaner implementation?

2023-03-01 13:17 UTC, olenagerasimova requested changes
@andpopov thanks, please, check my comment.

2023-03-01 13:17 UTC, olenagerasimova commented on docker-asto/AstoVersion.java
> +        fis.close();
Seems like almost each variable can be final and `try-with-recourses` or `try-finally` can be used to close `pom.xml` properly.

2023-03-01 14:06 UTC, dgarus commented
@ChGen 

> Maybe we should implement it as maven build profile as a next step, to have cleaner implementation?

Can additional dependencies be defined in a profile?

2023-03-02 05:54 UTC, ChGen commented
> @ChGen
> 
> > Maybe we should implement it as maven build profile as a next step, to have cleaner implementation?
> 
> Can additional dependencies be defined in a profile?

@dgarus , yes, profile may include dependencies:
```
........
  <profiles>
    <profile>
.........
      <repositories>...</repositories>
      <dependencies>...</dependencies>
      <dependencyManagement>...</dependencyManagement>
    </profile>
  </profiles>
```
https://maven.apache.org/pom.html#Profiles

2023-03-02 06:46 UTC, dgarus commented
@andpopov @ChGen @olenagerasimova 

The approach suggested in the PR doesn't look user-friendly.

Let's make two maven profiles:
 1. build with s3
 2. build with all storage implementations which we have.

In the release stage, make two docker images – first like now, second with active `build with s3` profile. There is no sense to using something excluding `fs` and `s3` to store artifacts, so we cover all existed cases.

wdyt?

2023-03-02 07:06 UTC, ChGen commented
> @andpopov @ChGen @olenagerasimova
> 
> The approach suggested in the PR doesn't look user-friendly.
> 
> Let's make two maven profiles:
> 
>     1. build with s3
> 
>     2. build with all storage implementations which we have.
> 
> 
> In the release stage, make two docker images – first like now, second with active `build with s3` profile. There is no sense to using something excluding `fs` and `s3` to store artifacts, so we cover all existed cases.
> 
> wdyt?

I think first profile should match current build configuration, stay slim in size, and second profile should contain all extra plugins with all their dependencies included, i.e. produce `artipie/artipie-full` docker image.

2023-03-02 07:10 UTC, dgarus commented
> second profile should contain all extra plugins

Why do you think it should contain all extra plugins?

2023-03-02 07:23 UTC, ChGen commented
> > second profile should contain all extra plugins
> 
> Why do you think it should contain all extra plugins?
Most people now start from artipie with file storage, so this is enough for basic image. Since we develop those extra plugins, we should provide proper way to try them. I think generating docker image for every plugin combination is overkill, so I'd prefer having full image instead. Another alternative would be providing user with script like in this PR to build the image for himself.

2023-03-02 07:42 UTC, dgarus commented
> > > second profile should contain all extra plugins
> > 
> > 
> > Why do you think it should contain all extra plugins?
> > Most people now start from artipie with file storage, so this is enough for basic image. Since we develop those extra plugins, we should provide proper way to try them. I think generating docker image for every plugin combination is overkill, so I'd prefer having full image instead. Another alternative would be providing user with script like in this PR to build the image for himself.


This makes sense. I suggest naming for profile somehow neutral and including to it only s3 plugin.
If there will be needing to include something else, we can easily to extend this profile.

2023-03-03 15:09 UTC, andpopov commented
I added all storage types to pom.xml and found the total size of artipie jars is increased +11 mega bytes (from 91 MB up to 102MB), so I seam it is reasonable to define all storage type dependencies in pom.xml without using workaround with extra logic.

2023-03-03 15:13 UTC, olenagerasimova commented
@andpopov and s3 works in this case? I'm not sure asto-s3 jar is a fat jar with dependencies...

2023-03-06 07:34 UTC, andpopov commented
> 

asto-s3 works

2023-03-07 08:35 UTC, olenagerasimova commented
Hm, seems reasonable
@dgarus what do you think?

2023-03-07 08:36 UTC, olenagerasimova submitted a review, later dismissed

2023-03-07 11:37 UTC, dgarus submitted a review, later dismissed
Thanks! LGTM

2023-03-07 13:53 UTC, olenagerasimova approved these changes

2023-03-07 13:53 UTC, olenagerasimova commented
@andpopov thanks

2023-03-07 14:01 UTC, merged