Wiki documentation for repository filters
artipie/artipie pull request #1275
Opened 2023-04-11 09:22 UTC by andpopov

Part of: #1254

2023-04-11 09:22 UTC, andpopov commented
@olenagerasimova, @dgarus, @ChGen Please review

2023-04-11 13:48 UTC, olenagerasimova requested changes
@andpopov thank, please, check my comments. Also, why are you using pair of two quotes `` for inline code? In wiki github markdown works fine and we use one quote for inline code in all wiki pages. I'm not sure how this pair of two quotes will look like after publishing...

2023-04-11 13:48 UTC, olenagerasimova commented on .wiki/Configuration-Repository.md
> +Each http-request to repository resource are controlled by filters.
are -> is ("each request" is single)

2023-04-11 13:48 UTC, olenagerasimova commented on .wiki/Configuration-Repository.md
> +- **glob** patters specify sets of resource locations with wildcard characters. Description of platform specific glob syntax is [here](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/jav
patters -> patterNs

2023-04-12 09:07 UTC, andpopov commented
@olenagerasimova Thanks a lot, I have corrected

2023-04-12 13:48 UTC, olenagerasimova approved these changes
thanks

2023-04-12 13:58 UTC, dgarus approved these changes
Looks good to me, thanks!

2023-04-12 14:24 UTC, merged