Documentation for Artipie scripting support
artipie/artipie pull request #1306
Opened 2023-08-08 10:08 UTC by ChGen

Documentation for Artipie scripting support. Part of https://github.com/artipie/artipie/issues/1277

2023-08-08 10:08 UTC, ChGen commented
@dgarus , please review.

2023-09-01 11:41 UTC, olenagerasimova reviewed
thanks, looks good. Though, I'd suggest to add simple script example (one, in any language) with access to artipie objects.

2023-09-04 10:33 UTC, ChGen commented
@dgarus , please review. I added snippet example.

2023-09-04 11:02 UTC, dgarus requested changes
Thanks!
There are a few minor comments.

2023-09-04 11:02 UTC, dgarus commented on .wiki/Configuration-Scripting.md
> +| `_settings`       | com.artipie.settings.Settings               |
It could be great to add links to the java docs or, at least, to files in the master branch.

2023-09-04 12:16 UTC, dgarus approved these changes
lgtm

2023-09-04 12:23 UTC, merged