feat: IT for metadata events
artipie/artipie pull request #1313
Opened 2023-09-27 15:25 UTC by olenagerasimova

part of #1291

2023-10-03 13:50 UTC, dgarus requested changes
Thanks!
There are a few minor comments.

2023-10-03 13:50 UTC, dgarus commented on .wiki/Configuration-Metadata.md
> +threads amount is limited to thread pool size.
```suggestion
threads amount is limited to the thread pool size.
```

2023-10-03 13:50 UTC, dgarus commented on .wiki/Configuration-Metadata.md
> +database file will be created at the parent location (directory) of the main configuration file. Metadata gathering
```suggestion
a database file will be created at the parent location (directory) of the main configuration file. The metadata gathering
```

2023-10-03 15:24 UTC, olenagerasimova commented
@dgarus thanks, applied all the suggestions and added database table name into wiki.

2023-10-04 06:12 UTC, dgarus approved these changes
Thanks!

2023-10-04 08:06 UTC, merged