S3 fixes (WIP)
artipie/artipie pull request #1396
Opened 2024-02-02 08:35 UTC by ChGen

S3 fixes (WIP)

2024-02-07 13:14 UTC, ChGen commented
@dgarus , please review.

2024-02-09 09:48 UTC, dgarus requested changes
Thanks.
Please check my comments

2024-02-09 09:48 UTC, dgarus commented on debian-adapter/pom.xml
> +        <exclusion>
Do we really need these commented dependencies here?

2024-02-09 09:48 UTC, dgarus commented on asto/asto-core/src/main/java/com/artipie/asto/rx/RxStorageWrapper.java
> +        )).observeOn(this.scheduler);
```suggestion
        return Single.defer(() -> SingleInterop.fromFuture(
            this.storage.value(key).thenCompose(CompletableFuture::completedFuture)
        )).observeOn(this.scheduler);
```

2024-02-09 09:48 UTC, dgarus commented on http-client/pom.xml
> +    <jettyVersion>12.0.6</jettyVersion>
`jettyVersion` property should be defined in the parent pom, isn't it?

2024-02-09 11:58 UTC, ChGen commented
@dgarus , please review.

2024-02-09 12:30 UTC, dgarus approved these changes

2024-02-09 12:51 UTC, merged