feat: remove ANONYMOUS field
artipie/artipie pull request #1412
Opened 2024-02-28 06:47 UTC by dgarus

Closes #1346

2024-02-28 14:57 UTC, ChGen requested changes
@dgarus , there's an extra empty line inside imports block in every changed file.

2024-02-28 14:57 UTC, ChGen commented on rpm-adapter/src/test/java/com/artipie/rpm/http/RpmSliceS3ITCase.java
> +
Redundant empty line.

2024-02-28 14:57 UTC, ChGen commented on rpm-adapter/src/test/java/com/artipie/rpm/http/RpmSliceITCase.java
Redundant empty line.

2024-02-28 14:57 UTC, ChGen commented on rpm-adapter/src/test/java/com/artipie/rpm/http/RpmSliceDownloadITCase.java
> +
Redundant empty line.

2024-02-28 14:57 UTC, ChGen commented on pypi-adapter/src/test/java/com/artipie/pypi/http/PySliceTest.java
Redundant empty line.

2024-02-28 14:57 UTC, ChGen commented on nuget-adapter/src/test/java/com/artipie/nuget/http/index/NuGetServiceIndexTest.java
Redundant empty line.

2024-02-28 14:57 UTC, ChGen commented on helm-adapter/src/test/java/com/artipie/helm/http/HelmDeleteIT.java
Redundant empty line.

2024-02-28 14:57 UTC, ChGen commented on helm-adapter/src/test/java/com/artipie/helm/HelmSliceIT.java
Redundant empty line.

2024-02-28 14:57 UTC, ChGen commented on go-adapter/src/test/java/com/artipie/http/GoSliceTest.java
Redundant empty line.

2024-02-28 14:57 UTC, ChGen commented on go-adapter/src/test/java/com/artipie/http/GoSliceITCase.java
Redundant empty line.

2024-02-28 14:57 UTC, ChGen commented on artipie-core/src/test/java/com/artipie/http/auth/AuthLoaderTest.java
> +
Redundant empty line.

2024-02-28 17:04 UTC, dgarus commented
> @dgarus , there's an extra empty line inside imports block in every changed file.

This line is between java lib's imports and others. 
This is a standard rule in the Java world.

2024-02-29 05:56 UTC, ChGen submitted a review, later dismissed
@dgarus , thanks.

2024-02-29 12:42 UTC, merged