Rpm proof
artipie/artipie pull request #418
Opened 2020-08-05 10:24 UTC by Sammers21

Related to #154

2020-08-18 14:57 UTC, Sammers21 commented
@g4s8, please review the Pull Request.

2020-08-19 08:55 UTC, olenagerasimova requested changes
@Sammers21 one suggestion, please, take a look

2020-08-19 08:55 UTC, olenagerasimova commented on examples/rpm/run.sh
> + /bin/bash -c "yum install -y yum-utils ; yum-config-manager --add-repo http://artipie:80/my-rpm/; yum --skip-broken --disablerepo='*' --enablerepo='80_my-rpm_' install wget"
@Sammers21 this line looks massive and difficult (time consuming) to read and understand. Maybe we could to split it into several steps?

2020-08-19 13:31 UTC, Sammers21 commented
@olenagerasimova, could you review the Pull Request once again, please?

2020-08-19 13:38 UTC, g4s8 requested changes
@Sammers21 please check my comment

2020-08-19 13:38 UTC, g4s8 commented on examples/rpm/run.sh
> +  yum install -y yum-utils ; \
@Sammers21 this test will not fail if any step fails, please use `/bin/bash -e -c "commands1; command2"` to fail CMD on step failure

2020-08-19 13:40 UTC, Sammers21 commented
@g4s8, review the PR one more time, please.

2020-08-19 14:44 UTC, olenagerasimova approved these changes
@Sammers21 thanks, looks good to me

2020-08-20 06:52 UTC, olegmoz approved these changes

2020-08-20 06:59 UTC, olegmoz commented
@Sammers21 `ppd-lint` workflow fails for this PR. Please exclude binary files from pdd check and we are good to merge

2020-08-20 07:00 UTC, olegmoz requested changes
@Sammers21 pdd fix needed

2020-08-20 08:42 UTC, olegmoz commented
@Sammers21 the proof is failing for some reason, could you please take a look?

2020-08-20 08:55 UTC, Sammers21 commented
@olegmoz, rpm proof is passing now.

2020-08-20 08:56 UTC, Sammers21 commented
@olegmoz, docker, and PyPI proof were broken in #457 PR and I've created an issue about it: #459

2020-08-20 09:02 UTC, olegmoz approved these changes
@Sammers21 thanks, merging it

2020-08-20 09:04 UTC, merged

2020-08-20 09:20 UTC, 0crat commented
Job `gh:artipie/artipie#418` is not assigned, can't get performer

<!-- https://www.0crat.com/footprint/CT2E6TK9B/23031694-950a-4afb-92cb-1ff9ba64cdc3, version: 0.54.5, hash: ${buildNumber} -->