535 - Add IT for deploying artifacts
artipie/artipie pull request #537
Opened 2020-09-01 08:03 UTC by genryxy

Part of #535 
Add IT for deploying release and snapshot artifacts. Also replace `StandardCharsets.UTF_8.displayName()` with `StandardCharsets.UTF_8` in `URLEncodedUtils.parse()` since this method was deprecated.

2020-09-02 13:24 UTC, olenagerasimova requested changes
@genryxy that's not quite what we need, tests in artipie should start whole artipie system, not individual adapter slice.

2020-09-07 10:21 UTC, g4s8 requested changes
@genryxy please check my comment

2020-09-07 14:15 UTC, genryxy commented
@olenagerasimova thanks, finally fixed, please take a look

2020-09-07 14:15 UTC, genryxy commented on src/test/java/com/artipie/maven/MavenITCase.java
> +            .forEach(
@g4s8 thanks, simplified

2020-09-08 06:29 UTC, olenagerasimova requested changes
@genryxy just one comment, please, take a look

2020-09-08 06:29 UTC, olenagerasimova commented on src/test/java/com/artipie/maven/MavenITCase.java
> +     * Executes dnf command in container.
@genryxy javadoc seems inaccurate, I think we can remove it as it's not required in tests and other methods have no comments

2020-09-08 06:43 UTC, genryxy commented
@olenagerasimova thanks, removed comment

2020-09-08 08:23 UTC, olenagerasimova approved these changes
@genryxy thanks

2020-09-09 13:13 UTC, merged

2020-09-09 13:30 UTC, 0crat commented
Job `gh:artipie/artipie#537` is not assigned, can't get performer

<!-- https://www.0crat.com/footprint/CT2E6TK9B/110bd2fa-508e-4e3a-a446-ae8a4fc96359, version: 0.54.5, hash: ${buildNumber} -->