Go proof
artipie/artipie pull request #541
Opened 2020-09-01 13:06 UTC by Sammers21

Closes #154
Closes #540

2020-09-01 14:45 UTC, olegmoz requested changes
@Sammers21 thanks, all looks good, have one concern though. Please see the comment

2020-09-01 14:45 UTC, olegmoz commented on examples/go/run.sh
> +export GOPROXY=http://localhost:8080/my-go-proxy
@Sammers21 I see that Go uses word proxy for custom artifacts manager, but it is a bit misleading in context of Artipie. We have proxy type of adapters and someday going to have proxy for Go as well. I'd suggest to remove proxy word from repo name

2020-09-02 06:35 UTC, olegmoz approved these changes
@Sammers21 thanks, merging

2020-09-02 07:16 UTC, olegmoz requested changes
@Sammers21 the proof is failing after recent changes, please fix

2020-09-02 07:57 UTC, olegmoz approved these changes
@Sammers21 thanks

2020-09-02 07:58 UTC, merged

2020-09-02 08:16 UTC, 0crat commented
Job `gh:artipie/artipie#541` is not assigned, can't get performer

<!-- https://www.0crat.com/footprint/CT2E6TK9B/e1931783-5bf5-4db6-98ec-5625c360b6c2, version: 0.54.5, hash: ${buildNumber} -->