Publish benchmarks results
artipie/artipie pull request #547
Opened 2020-09-03 13:49 UTC by Sammers21

Remove old and publish new benchmarks results for artipie versions 0.10 0.9.5 0.9.3 0.9.2 0.9.1

2020-09-03 13:59 UTC, Sammers21 commented
@olegmoz, can you review this PR, please?

2020-09-03 14:40 UTC, olegmoz requested changes
@Sammers21 I am not sure that it is good idea to remove all older benchmark results right away. Maybe it would be better to keep them until visualization of new benchmark results is ready

2020-09-04 12:12 UTC, Sammers21 commented
@olegmoz, can we merge?

2020-09-04 12:57 UTC, olegmoz approved these changes
@Sammers21 thanks, merging

2020-09-04 12:57 UTC, merged

2020-09-04 13:14 UTC, 0crat commented
Job `gh:artipie/artipie#547` is not assigned, can't get performer

<!-- https://www.0crat.com/footprint/CT2E6TK9B/ed57bb89-02e4-4919-a2b7-da78bb71622f, version: 0.54.5, hash: ${buildNumber} -->