#549 - Added JoinedPermissions
artipie/artipie pull request #556
Opened 2020-09-09 11:09 UTC by olegmoz

Part of #549 
Added `JoinedPermissions` class to be used for composing global permissions and repo permissions

2020-09-09 13:08 UTC, olenagerasimova requested changes
@olegmoz thanks, just one suggestion, please, take a look

2020-09-09 13:08 UTC, olenagerasimova commented on src/main/java/com/artipie/auth/JoinedPermissions.java
> +    public JoinedPermissions(final Collection<Permissions> origins) {
@olegmoz I'd suggest to add secondary ctor from `Permissions... origins`

2020-09-09 13:15 UTC, olegmoz commented
@olenagerasimova thanks, added varargs constructor. Please review

2020-09-09 13:51 UTC, olenagerasimova approved these changes
@olegmoz thanks, good to merge

2020-09-10 05:50 UTC, merged

2020-09-10 06:08 UTC, 0crat commented
Job `gh:artipie/artipie#556` is not assigned, can't get performer

<!-- https://www.0crat.com/footprint/CT2E6TK9B/13351f0a-8af8-495b-a29e-79a4f9e4ff4e, version: 0.54.5, hash: ${buildNumber} -->