Gem docs updated
artipie/artipie pull request #590
Opened 2020-09-14 13:43 UTC by Sammers21

Gem docs have been updated.

Related to #361

2020-09-14 15:30 UTC, olenagerasimova requested changes
@Sammers21 two comments, take a look please

2020-09-14 15:30 UTC, olenagerasimova commented on examples/gem/README.md
> +In order to upload a `.gem` file into, use `gem push` command:
@Sammers21 seems like several words before comma are missing

2020-09-14 15:30 UTC, olenagerasimova commented on examples/gem/README.md
> +In order to install an existing gem , use `gem install` command:
@Sammers21 please remove space before comma

2020-09-15 07:17 UTC, olenagerasimova approved these changes
@Sammers21 thanks
@olegmoz looks good to merge

2020-09-16 10:42 UTC, olegmoz approved these changes

2020-09-16 11:22 UTC, merged

2020-09-16 12:00 UTC, 0crat commented
Job `gh:artipie/artipie#590` is not assigned, can't get performer

<!-- https://www.0crat.com/footprint/CT2E6TK9B/9be37fd6-f07c-4b1b-b261-47c2d94f2586, version: 0.54.5, hash: ${buildNumber} -->