GOPROXY docs improved
artipie/artipie pull request #591
Opened 2020-09-14 13:58 UTC by Sammers21

Related to #361.

2020-09-15 07:28 UTC, olenagerasimova requested changes
@Sammers21 added comments, take a look please

2020-09-15 07:28 UTC, olenagerasimova commented on examples/go/README.md
> +After creating the configuration file below, the configured GOPROXY is ready for use. First, you have to declare the following environment variables:
@Sammers21 `First` seems odd as there is no `second` or something similar

2020-09-15 07:28 UTC, olenagerasimova commented on examples/go/README.md
> +export GOPROXY="http://localhost:8080/my-go,https://proxy.golang.org,direct"
@Sammers21 I do not think we need two configuration examples, `go` developers should know that `GOPROXY` excepts list and it's highly unlikely that someone do not need to stay connected to central

2020-09-16 09:21 UTC, olenagerasimova approved these changes
@Sammers21 thanks
@olegmoz thanks, looks good to merge

2020-09-16 10:41 UTC, olegmoz approved these changes

2020-09-16 11:06 UTC, merged

2020-09-16 11:24 UTC, 0crat commented
Job `gh:artipie/artipie#591` is not assigned, can't get performer

<!-- https://www.0crat.com/footprint/CT2E6TK9B/ffef0c0f-3cac-4634-9cd8-127db6e079fc, version: 0.54.5, hash: ${buildNumber} -->