#604 - rpm upload
artipie/artipie pull request #659
Opened 2020-10-05 13:57 UTC by olenagerasimova

Part of #604 
Created test for rpm upload.

2020-10-05 14:35 UTC, olegmoz requested changes
@olenagerasimova thanks, please see two minor comments

2020-10-05 14:35 UTC, olegmoz commented on src/test/java/com/artipie/rpm/RpmITCase.java
> +        }
@olenagerasimova I'd suggest to use `ByteStreams.copy` from Guava library here for copying of bytes, it will simplify code a little bit

2020-10-05 14:35 UTC, olegmoz commented on src/test/java/com/artipie/rpm/RpmITCase.java
> +    private String configs() {
@olenagerasimova guess there is typo and this method's name is supposed to be `config`, not `configs`, isn't it?

2020-10-05 14:37 UTC, olegmoz commented
@olenagerasimova also please not that PDD linter failing on new binary file, it has to be excluded

2020-10-05 16:14 UTC, olenagerasimova commented
@olegmoz thanks, all corrected

2020-10-06 13:09 UTC, olegmoz approved these changes
@olenagerasimova thanks. merging

2020-10-06 14:39 UTC, merged

2020-10-06 14:58 UTC, 0crat commented
Job `gh:artipie/artipie#659` is not assigned, can't get performer

<!-- https://www.0crat.com/footprint/CT2E6TK9B/a7b030da-4f4a-4c70-a9c6-0f3ae2f56f0a, version: 0.54.5, hash: ${buildNumber} -->