#652 - Verify with authentication in pypiIT
artipie/artipie pull request #682
Opened 2020-10-09 09:39 UTC by genryxy

Closes #652 
Verify package installation and  package publishing with authentication in `pypiITCase`

2020-10-09 10:48 UTC, olenagerasimova requested changes
@genryxy just minor comment, take a look please

2020-10-09 10:48 UTC, olenagerasimova commented on src/test/java/com/artipie/pypi/PypiITCase.java
> +                )
@genryxy `RepoPerms` now has ctor from two strings (name and password), so this expression can be simplified

2020-10-09 10:58 UTC, genryxy commented
@olenagerasimova thanks, replaced ctor

2020-10-09 11:17 UTC, olenagerasimova commented
@genryxy thanks
@olegmoz good to merge

2020-10-09 12:07 UTC, olegmoz commented
@olenagerasimova please approve the PR

2020-10-09 15:17 UTC, olenagerasimova approved these changes

2020-10-12 07:46 UTC, merged

2020-10-12 08:03 UTC, 0crat commented
Job `gh:artipie/artipie#682` is not assigned, can't get performer

<!-- https://www.0crat.com/footprint/CT2E6TK9B/26b08859-9be6-4342-bdc8-57b8462106b9, version: 0.54.5, hash: ${buildNumber} -->