#605 - Verify publish in NpmITCase
artipie/artipie pull request #717
Opened 2020-10-23 13:26 UTC by genryxy

Part of #605 
Verify that npm publish project without authentication is working.

2020-10-23 14:52 UTC, olegmoz requested changes
@genryxy thanks, please see two comments

2020-10-23 14:52 UTC, olegmoz commented on src/test/java/com/artipie/npm/NpmITCase.java
> +            new StringContains("+ @hello/simple-npm-project@1.0.1")
@genryxy it looks like `proj` is part of the string, I'd suggest to use it

2020-10-23 14:52 UTC, olegmoz commented on src/test/java/com/artipie/npm/NpmITCase.java
> +            ).toCompletableFuture().join(),
@genryxy `.tgz` file path is constructed twice here, I'd suggest to extract into variable

2020-10-23 15:28 UTC, genryxy commented
@olegmoz thanks, corrected

2020-10-26 07:32 UTC, olegmoz approved these changes
@genryxy thanks, merging

2020-10-26 07:32 UTC, merged

2020-10-26 08:07 UTC, 0crat commented
Job `gh:artipie/artipie#717` is not assigned, can't get performer

<!-- https://www.0crat.com/footprint/CT2E6TK9B/081d05be-41ed-48e6-b2d0-c032c150d9b0, version: 0.54.5, hash: ${buildNumber} -->