#835 - upload install test
artipie/artipie pull request #837
Opened 2021-01-18 14:47 UTC by olenagerasimova

Part of #835
Added test case for upload and install

2021-01-18 17:03 UTC, genryxy requested changes
@olenagerasimova thanks, one suggestion

2021-01-18 17:03 UTC, genryxy commented on src/test/java/com/artipie/debian/DebianITCase.java
>          this.cntn = new GenericContainer<>("debian")
@olenagerasimova I'd suggest to use `TestContainer` class here

2021-01-19 05:48 UTC, olenagerasimova commented
@genryxy thanks, corrected

2021-01-19 06:09 UTC, genryxy approved these changes
@olenagerasimova thanks, looks good to me

2021-01-19 07:40 UTC, merged

2021-01-19 08:06 UTC, 0crat commented
Job `gh:artipie/artipie#837` is not assigned, can't get performer

<!-- https://www.0crat.com/footprint/CT2E6TK9B/8145ed71-0db3-4711-a840-abc5fb4afd7d, version: 0.55, hash: ${buildNumber} -->