IT for debian-adapter with TestDeployment
artipie/artipie pull request #873
Opened 2021-03-18 13:36 UTC by olenagerasimova

Part of #855 
Updated debian adapter and remade integration test for it with `TestDeployment`. 
Extended `MavenITCase.ContainerResultMatcher` with matcher for stdout and ctors.

2021-03-18 14:42 UTC, genryxy submitted a review, later dismissed
@olenagerasimova thanks, looks good to me
@g4s8 please check/merge

2021-03-19 08:31 UTC, g4s8 requested changes
@olenagerasimova please check my comments

2021-03-19 08:31 UTC, g4s8 commented on src/test/java/com/artipie/debian/DebianITCase.java
> +            "Move debian sources",
@olenagerasimova it's failure message that prints if assertion fails, similar to `AssertMatcher.assertThat(msg, ...)`

2021-03-19 08:31 UTC, g4s8 commented on src/test/java/com/artipie/debian/DebianITCase.java
> +            "Deb package uploaded",
@olenagerasimova same here

2021-03-19 08:31 UTC, g4s8 commented on src/test/java/com/artipie/debian/DebianITCase.java
> +            "Apt-get update successful",
@olenagerasimova and here

2021-03-19 08:39 UTC, olenagerasimova commented
@g4s8 thanks, corrected messages

2021-03-19 08:52 UTC, g4s8 approved these changes
@olenagerasimova thanks

2021-03-19 08:52 UTC, merged

2021-03-19 09:17 UTC, 0crat commented
Job `gh:artipie/artipie#873` is not assigned, can't get performer

<!-- https://www.0crat.com/footprint/CT2E6TK9B/11d45d26-e23e-44a2-b959-f99e23e7f7b8, version: 0.55.1, hash: ${buildNumber} -->