Npm IT with TestDeployment
artipie/artipie pull request #882
Opened 2021-04-26 14:30 UTC by olenagerasimova

Part of #855 
Remade `NpmITCase` to use `TestDeployment`

2021-04-26 15:39 UTC, genryxy requested changes
@olenagerasimova thanks, one minor suggestion

2021-04-26 15:39 UTC, genryxy commented on src/test/java/com/artipie/npm/NpmITCase.java
> +                        String.format("+ %s@1.0.1", NpmITCase.PROJ),
@olenagerasimova I'd suggest to extract this string as it is used twice

2021-04-27 06:54 UTC, olenagerasimova commented
@genryxy thanks, extracted

2021-04-27 07:38 UTC, genryxy approved these changes
@olenagerasimova thanks, approve

2021-04-27 10:52 UTC, merged