feat: add TTL and max size for cache storages in proxy repos
artipie/artipie pull request #932
Opened 2021-08-31 15:17 UTC by genryxy

Part of #334 
Added interface for obtaining TTL and max size values from config of repo. In next PR, I'm planning to add some tests

2021-09-01 06:35 UTC, olenagerasimova requested changes
@genryxy thanks, please, take a look, I have naming suggestions

2021-09-01 06:35 UTC, olenagerasimova commented on src/main/java/com/artipie/repo/YamlCacheStorage.java
> +    private final Storage cstorage;
I'd suggest to simplify field name to `asto`

2021-09-01 06:35 UTC, olenagerasimova commented on src/main/java/com/artipie/repo/YamlCacheStorage.java
> +    private final Long cmaxsize;
And here to `size`

2021-09-01 07:51 UTC, genryxy commented
@olenagerasimova thanks, renamed

2021-09-01 07:52 UTC, olenagerasimova commented
@genryxy thanks, looks good to me
@g4s8 please, take a look/merge

2021-09-01 08:31 UTC, genryxy commented
One integration test fails although changes are not related to this
```
[INFO] Running com.artipie.api.ArtipieApiITCase
artipie/artipie:1.0-SNAPSHOT - artipie: [INFO] 2021-09-01 08:27:10,824 main com.artipie.VertxMain - Used version of Artipie: 1.0-SNAPSHOT
Error: /artipie:1.0-SNAPSHOT - artipie: [ERROR] Tests run: 3, Failures: 1, Errors: 0, Skipped: 2, Time elapsed: 3.808 s <<< FAILURE! - in com.artipie.api.ArtipieApiITCase
Error:  com.artipie.api.ArtipieApiITCase.dashboardIsUp  Time elapsed: 3.803 s  <<< FAILURE!
java.lang.AssertionError: 
Artipie dashboard is not up and running
Expected: status is <0>stdout a string containing "<!DOCTYPE html>", "<title>alice</title>", "Your repositories:" in order
     but: failed with status:
<7>
STDOUT: 
```

2021-09-01 08:51 UTC, olenagerasimova commented
@genryxy ubuntu 11 log says it's ok
```
rtipie:1.0-SNAPSHOT - artipie: [WARNING] Tests run: 3, Failures: 0, Errors: 0, Skipped: 2, Time elapsed: 3.427 s - in com.artipie.api.ArtipieApiITCase
```

2021-09-02 07:56 UTC, genryxy commented
@g4s8 could you please take a look

2021-09-03 12:11 UTC, g4s8 approved these changes
@genryxy thanks

2021-09-03 12:16 UTC, g4s8 commented
@olenagerasimova please click approve if this PR is OK for you

2021-09-03 12:27 UTC, olenagerasimova approved these changes

2021-09-03 12:27 UTC, merged