test: smoke tests fixed
artipie/artipie pull request #939
Opened 2021-09-10 13:30 UTC by g4s8

Fixed runner script, fail on error

Ticket: #847

2021-09-10 14:18 UTC, olenagerasimova requested changes
@g4s8 one question, take a look please

2021-09-10 14:18 UTC, olenagerasimova commented on examples/run.sh
> +  declare -a tests=(binary debian docker go helm maven npm nuget php rpm)
Why conda is not in the list?

2021-09-13 09:09 UTC, olenagerasimova commented
@g4s8 please, resolve conflicts and we are good to merge

2021-09-13 09:29 UTC, g4s8 commented
@olenagerasimova thanks, resolved

2021-09-13 10:44 UTC, olenagerasimova approved these changes

2021-09-14 09:42 UTC, merged