refactor: extract cache package and logic of reading property value
artipie/artipie pull request #963
Opened 2021-11-03 11:06 UTC by genryxy

Part of #87 

- Extracted `cache` package.
- Extracted logic of reading value of the property from environment and Artipie properties file.
- Fixed reading value of property and added tests for it. Now it takes value of property from environment, if it was set, otherwise it looks up in `artipie.properties` file. If both of them are `null` it parses to long passed default value.

2021-11-03 12:16 UTC, olenagerasimova requested changes
@genryxy thanks, added some comments, take a look, please

2021-11-03 12:16 UTC, olenagerasimova commented on src/main/java/com/artipie/misc/Property.java
> +     * with values of the properties.
This sentence seems off, please, check

2021-11-03 12:16 UTC, olenagerasimova commented on src/main/java/com/artipie/misc/Property.java
> +     * @return Long value of or default value.
and this one too

2021-11-03 12:16 UTC, olenagerasimova commented on src/main/java/com/artipie/misc/Property.java
> +    public long asLongOrDefault(final String defval) {
I'd suggest to change type of the parameter from String to long, as this method is designed to obtain and return longs

2021-11-03 12:35 UTC, genryxy commented
@olenagerasimova thanks, corrected

2021-11-08 06:53 UTC, olenagerasimova approved these changes
@genryxy thanks

2021-11-08 06:55 UTC, olenagerasimova commented
@g4s8 please, take a look/merge

2021-11-08 08:05 UTC, merged