test: add more tests for creds cache
artipie/artipie pull request #966
Opened 2021-11-10 15:03 UTC by genryxy

Part of #87 
Added more tests for credentials cache

2021-11-11 07:44 UTC, olenagerasimova requested changes
@genryxy thanks, just one minor comment

2021-11-11 07:44 UTC, olenagerasimova commented on src/test/java/com/artipie/YamlSettingsTest.java
> +        );
Please, add mismatch description to this assertion

2021-11-11 08:24 UTC, genryxy commented
@olenagerasimova thanks, added

2021-11-11 09:38 UTC, olenagerasimova approved these changes
@genryxy thanks

2021-11-15 05:22 UTC, genryxy commented
@g4s8 could you please check/merge

2021-11-15 08:37 UTC, merged