Test for `/api/security/users` endpoint
artipie/artipie pull request #969
Opened 2021-11-16 06:53 UTC by olenagerasimova

Part of #965 
Updated management-api, asto, http and added IT for `/api/security/users` endpoint.
Also, due to `NoSuchMethod` runtime exception with hamcrest `Matchers.allOff` method in one of the tests, added hamcrest dependency.

2021-11-16 07:14 UTC, genryxy requested changes
@olenagerasimova thanks, two questions

2021-11-16 07:14 UTC, genryxy commented on pom.xml
> +    <maven.compiler.target>11</maven.compiler.target>
why version was downgraded?

2021-11-16 07:14 UTC, genryxy commented on src/test/java/com/artipie/api/ArtipieApiITCase.java
> +                )
is the order for names in this line determined?

2021-11-16 08:32 UTC, olenagerasimova commented
@genryxy thanks

2021-11-16 08:41 UTC, genryxy submitted a review, later dismissed
@olenagerasimova thanks, looks good to me
@g4s8 please check/merge

2021-11-17 14:00 UTC, g4s8 requested changes
@olenagerasimova just one comment

2021-11-17 14:00 UTC, g4s8 commented on pom.xml
> +      </plugins>
Why Java lang version changed?

2021-11-17 14:24 UTC, olenagerasimova commented on pom.xml
> +      </plugins>
my bad, sorry

2021-11-17 14:25 UTC, olenagerasimova commented
@g4s8 thanks, fixed

2021-11-18 12:23 UTC, olenagerasimova commented
@g4s8 please, merge

2021-11-23 06:33 UTC, olenagerasimova commented
@g4s8 ping

2021-11-23 06:35 UTC, genryxy approved these changes

2021-11-23 06:36 UTC, g4s8 approved these changes
@olenagerasimova thanks

2021-11-23 06:36 UTC, merged