feat: add repo delete and bump deps
artipie/artipie pull request #981
Opened 2021-12-27 09:52 UTC by genryxy

Closes #321 
Implemented repo delete and bumped `asto` to `v1.11.0` and `api` to `v0.5.1`.
Get name without extension in `RepositoriesFromStorage`

2021-12-27 10:09 UTC, olenagerasimova requested changes
@genryxy please, check my comment

2021-12-27 10:09 UTC, olenagerasimova commented on src/main/java/com/artipie/MeasuredStorage.java
> +        return this.origin.metadata(key);
Every method of `MeasuredStorage` logs execution time, I'd suggest logging it here too

2021-12-27 10:29 UTC, genryxy commented
@olenagerasimova thanks, corrected

2021-12-27 10:42 UTC, olenagerasimova approved these changes
@genryxy thanks, looks good

2021-12-27 11:36 UTC, genryxy commented
@olenagerasimova I've disabled conda install IT case because it fails with out of storage [exception](https://github.com/artipie/artipie/runs/4641400517?check_suite_focus=true#step:6:2241) after bumping asto to `v1.11.0`

2021-12-27 11:37 UTC, genryxy commented
@g4s8 could you please check / merge

2022-01-11 11:57 UTC, genryxy commented
@g4s8 could you please check

2022-02-09 15:55 UTC, g4s8 approved these changes
@genryxy thanks

2022-02-09 15:55 UTC, merged